"""empty message

Revision ID: 05984f33a171
Revises: b7d809f32074
Create Date: 2018-05-08 18:41:04.670109

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05984f33a171'
down_revision = 'b7d809f32074'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('head_img', sa.String(length=45), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'head_img')
    # ### end Alembic commands ###
