"""empty message

Revision ID: 217d47302b6d
Revises: 97692e36d0a3
Create Date: 2018-05-04 20:50:31.753772

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '217d47302b6d'
down_revision = '97692e36d0a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('body_html', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'body_html')
    # ### end Alembic commands ###
